
export const USA_STATES =[
    ['us', 0, ' All states'],
    ['us-ma', 1, 'Massachusetts'],
    ['us-wa', 2, 'Washington'],
    ['us-ca', 3, 'California'],
    ['us-or', 4, 'Oregon'],
    ['us-wi', 5, 'Wisconsin'],
    ['us-me', 6, 'Maine'],
    ['us-mi', 7, 'Michigan'],
    ['us-nv', 8, 'Nevada'],
    ['us-nm', 9, 'New Mexico'],
    ['us-co', 10, "Colorado"],
    ['us-wy', 11, 'Wyoming'],
    ['us-ks', 12, 'Kansas'],
    ['us-ne', 13, 'Nebraska'],
    ['us-ok', 14, 'Oklahoma'],
    ['us-mo', 15, 'Missouri'],
    ['us-il', 16, 'Illinois'],
    ['us-in', 17, 'Indiana'],
    ['us-vt', 18, 'Vermont'],
    ['us-ar', 19, 'Arkansas'],
    ['us-tx', 20, 'Texas'],
    ['us-ri', 21, 'Rhode Island'],
    ['us-al', 22, 'Alabama'],
    ['us-ms', 23, 'Mississippi'],
    ['us-nc', 24, 'North Carolina'],
    ['us-va', 25, 'Virginia'],
    ['us-ia', 26, 'Iowa'],
    ['us-md', 27, 'Maryland'],
    ['us-de', 28, 'Delaware'],
    ['us-pa', 29, 'Pennsylvania'],
    ['us-nj', 30, 'New Jersey'],
    ['us-ny', 31, 'New York'],
    ['us-id', 32, 'Idaho'],
    ['us-sd', 33, 'South Dakota'],
    ['us-ct', 34, 'Connecticut'],
    ['us-nh', 35, 'New Hampshire'],
    ['us-ky', 36, 'Kentucky'],
    ['us-oh', 37, 'Ohio'],
    ['us-tn', 38, 'Tennessee'],
    ['us-wv', 39, 'West Virginia'],
    ['us-dc', 40, 'District of Columbia'],
    ['us-la', 41, 'Louisiana'],
    ['us-fl', 42, 'Florida'],
    ['us-ga', 43, 'Georgia'],
    ['us-sc', 44, 'South Carolina'],
    ['us-mn', 45, 'Minnesota'],
    ['us-mt', 46, 'Montana'],
    ['us-nd', 47, 'North Dakota'],
    ['us-az', 48, 'Arizona'],
    ['us-ut', 49, 'Utah'],
    ['us-hi', 50, 'Hawaii'],
    ['us-ak', 51, 'Alaska']
].sort(function (a, b) {
    return ('' + a[2]).localeCompare(b[2]);
})